// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/duty-log/CleanBold.tsx": () => import("../components/mockups/duty-log/CleanBold.tsx"),
  "./components/mockups/duty-log/CommandCenter.tsx": () => import("../components/mockups/duty-log/CommandCenter.tsx")
};
